language: java
jdk: oraclejdk11

script: mvn -e verify

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: hw-autoservice

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - spartars@yandex.ru
    on_failure: always
    on_success: change